### PR TITLE
ps2packer: Fix building with recent ps2sdk

### PR DESCRIPTION
**Pull request by Caio99BR**
* Fix for https://travis-ci.org/Caio99BR/Open-PS2-Loader/builds/193160246

### CODE REVIEW

**Comment by sp193** [comment]
libsyscall is probably the one from Newlib. Did you build and install your toolchain from the first to last phase? Particularly, phase 3 (Newlib).

But because it does not seem that ps2-packer's stubs actually need libsyscall (no cpp files), there is probably no harm in removing it.

**Comment by Caio99BR** [comment]
Yes, I builded all (In TraviCI and in my PC), both only build with this fix.
Anyway I will check it again on TravisCI

**Comment by Caio99BR** [comment]
Hmm, ps2toolchain is generating a too big log (4,9MB), not like before.
The log is here: https://transfer.sh/49VBt/opnps2ld-ps2toolchain-caio99br-nightly13.log
The OPL build is here too: https://transfer.sh/14wIT/opnps2ld-0.9.3-.993-beta-f6a8c37-caio99br-nightly13.zip
I can't tested it now

**Comment by sp193** [comment]
Okay, that's weird... now I can't build ps2-packer. But I know that I have built it before because I have been using it for years. Hmm.

Neither can I find any trace of this "libsyscall" among the libraries under $PS2DEV/ee/ee/lib. I guess that this will do for now.
If anyone has other issues related to Newlib that gives a clearer picture of the problem, then we'll do something about it.

**Pull request merged**
